### ISSUE TITLE
src/renderer/media.js似乎没有导入ntCall

### ISSUE THREAD

**Issue by zklin99** [Night-stars-1/LiteLoaderQQNT-Plugin-LLAPI#2]
src/renderer/media.js下的Media类使用了ntCall函数但是没有导入，导致发图片会失败

自己尝试在该文件加上下面这句后就可以发图片了
`
import { ntCall } from "./utils.js";
`

我是在写scriptio插件的脚本的时候遇到的

**Comment by Night-stars-1** [comment]
更新反馈，已修复
